abstract: Convert between ASCII text and MORSE alphabet
author: Tels <nospam-abuse@bloodgate.com>
build_requires: 
  Test::More: 0.47
distribution_type: module
generated_by: Module::Install version 0.64
license: gpl
name: Convert-Morse
no_index: 
  directory: 
    - inc
    - t
requires: 
  perl: 5.8.1
version: 0.05
